name: seguimiento_de_construcion
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2  # Verifica que sea compatible
  firebase_auth_web: ^5.14.2 
  google_sign_in: ^6.3.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  provider: ^6.0.5
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.3 
  cloud_firestore: ^5.6.6
  flutter_image_compress: ^2.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17  # Se agregó la dependencia de mockito
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
