// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9mNkLyllq67wErMrN1oYylyymJNOpMkk',
    appId: '1:199538053199:android:b22e210b6af1043d539a3a',
    messagingSenderId: '199538053199',
    projectId: 'seguimiento-carlos-2025',
    storageBucket: 'seguimiento-carlos-2025.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-8bAn1hR49JjVjmPZh3qNZXS_ZZjfdqY',
    appId: '1:199538053199:web:a217f0a60f3ab169539a3a',
    messagingSenderId: '199538053199',
    projectId: 'seguimiento-carlos-2025',
    authDomain: 'seguimiento-carlos-2025.firebaseapp.com',
    storageBucket: 'seguimiento-carlos-2025.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHnNIW4Gw6Zr8-RX0IFu3xroF9ttxjoVk',
    appId: '1:199538053199:ios:3389c78620e6f4df539a3a',
    messagingSenderId: '199538053199',
    projectId: 'seguimiento-carlos-2025',
    storageBucket: 'seguimiento-carlos-2025.firebasestorage.app',
    iosClientId: '199538053199-ojglc8iv868qffgueuf3h9dmhrm2hetl.apps.googleusercontent.com',
    iosBundleId: 'com.example.seguimientoDeConstrucion',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHnNIW4Gw6Zr8-RX0IFu3xroF9ttxjoVk',
    appId: '1:199538053199:ios:3389c78620e6f4df539a3a',
    messagingSenderId: '199538053199',
    projectId: 'seguimiento-carlos-2025',
    storageBucket: 'seguimiento-carlos-2025.firebasestorage.app',
    iosClientId: '199538053199-ojglc8iv868qffgueuf3h9dmhrm2hetl.apps.googleusercontent.com',
    iosBundleId: 'com.example.seguimientoDeConstrucion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-8bAn1hR49JjVjmPZh3qNZXS_ZZjfdqY',
    appId: '1:199538053199:web:919374ae73c6bcda539a3a',
    messagingSenderId: '199538053199',
    projectId: 'seguimiento-carlos-2025',
    authDomain: 'seguimiento-carlos-2025.firebaseapp.com',
    storageBucket: 'seguimiento-carlos-2025.firebasestorage.app',
  );

}